# code: language=YAML tabSize=2

# General
site_name: M42PL - Core commands

# Navigation
nav:
  - "Home": "index.md"
  - "Commands type": "tags.md"
  - ...

# Source repository
repo_url: https://github.com/jpclipffel/m42pl-commands
repo_name: jpclipffel/m42pl-commands
edit_uri: ""
src_uri: ""

# Markdown extensions
markdown_extensions:
  - meta
  - admonition

# Plugins
plugins:
  - search
  - awesome-pages
  - tags:
      tags_file: tags.md

# Theme confoguration
theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: default
      primary: black
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: "assets/Logo - Text - White.png"
  favicon: "assets/Logo - Text - White.png"